### ISSUE TITLE
se rompe todo con las series que arrancan con la misma palabra

### ISSUE THREAD

**Issue by jugoprex** [SanFlan/bot-disc#6]
```
Ignoring exception in command change_view_date:
Traceback (most recent call last):
  File "/home/juli/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/juli/bot-disc/bot.py", line 279, in change_view_date
    set_date_to_entry(entry, new_date)
  File "/home/juli/bot-disc/db/__init__.py", line 115, in set_date_to_entry
    entry = get_entry_from_name(entry_name)
  File "/home/juli/bot-disc/db/__init__.py", line 59, in get_entry_from_name
    entry = session.query(Entry).filter(
  File "/home/juli/.local/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 3467, in one_or_none
    raise orm_exc.MultipleResultsFound(
sqlalchemy.orm.exc.MultipleResultsFound: Multiple rows were found for one_or_none()

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/juli/.local/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 902, in invoke
    await ctx.command.invoke(ctx)
  File "/home/juli/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 864, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/juli/.local/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: MultipleResultsFound: Multiple rows were found for one_or_none()
```

**Comment by SanFlan** [comment]
Esto esta arreglado hace un tiempo ¿recuerdan en que commit fue?

**Comment by SanFlan** [comment]
No se pudo replicar el error, queda cerrado por ahora.

**Comment by SanFlan** [comment]
Se pudo replicar, pasos para replicar:
add Francia en llamas
add Francia en bolas
chd Francia
